name: rwkv_dart
description: "rwkv llm dart sdk"
publish_to: https://pub.dev
repository: https://github.com/dengzii/rwkv_dart
issue_tracker: https://github.com/dengzii/rwkv_dart/issues
version: 1.1.2
topics:
  - rwkv
  - llm

environment:
  sdk: ^3.8.0

dependencies:
  ffi: ^2.1.5
  logging: ^1.3.0
  dio: ^5.9.0
  shelf: ^1.4.2
  fetch_client: ^1.2.0
  dio_compatibility_layer: ^0.1.0

dev_dependencies:
  test: